# Configuration: [x, y, yaw, j1, j2, j3, j4, j5, j6] 9-DOFs
# Topology space:[R, R, SO2,  R,  R,  R,  R,  R,  R]
qlimit: [
    10.0,
    10.0,
    0.0, # this bound is ignored as it is SO2 type.
    6.28318530718,
    6.28318530718,
    6.28318530718,
    6.28318530718,
    6.28318530718,
    6.28318530718,
  ]

qstart: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

qgoal: [3.0, 3.0, 1.57, 0.0, -1.57, 0.0, 0.0, 1.57, 0.0]

range: 0.3
bias: 0.05
time_limit: 2.0
simplify_solution: false

path_save_planner_data: paper_mm_simple_planner_data
path_save_start_goal: paper_mm_simple_start_goal
path_save_path: paper_mm_simple_path
