robot:
  l1: 2.0
  l2: 2.0

env:
  rectangles:
    - [-0.7, 1.3, 2.0, 2.2]
    - [2.0, -2.0, 1.0, 4.0]
    - [-3.0, -3.0, 1.25, 2.0]

qlimit: [6.28318530718, 6.28318530718] # 2 * PI

qstart: [2.68, -2.86]

qgoal: [-0.70, 1.73]

range: 0.3
bias: 0.05
time_limit: 2.0
simplify_solution: true

path_save_planner_data: paper_r2s_extsgoalset_planner_data
path_save_start_goal: paper_r2s_extsgoalset_start_goal
path_save_path: paper_r2s_extsgoalset_path
